// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3HrjHRyRhW4PAlEyZRr2w9ohu-fpwwUY',
    appId: '1:849429187790:web:4ce39298e0cbc9c6bf549f',
    messagingSenderId: '849429187790',
    projectId: 'barras-762b5',
    authDomain: 'barras-762b5.firebaseapp.com',
    storageBucket: 'barras-762b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBczVp0zqLx4skoK3kZZdpnBm2z634G_Jo',
    appId: '1:849429187790:android:f95a5653501a99b1bf549f',
    messagingSenderId: '849429187790',
    projectId: 'barras-762b5',
    storageBucket: 'barras-762b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHl-usFnkO1HORrJ-wFpjvicxz-ilKmNw',
    appId: '1:849429187790:ios:e60a10af6297c203bf549f',
    messagingSenderId: '849429187790',
    projectId: 'barras-762b5',
    storageBucket: 'barras-762b5.firebasestorage.app',
    iosBundleId: 'com.example.codigobarras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHl-usFnkO1HORrJ-wFpjvicxz-ilKmNw',
    appId: '1:849429187790:ios:e60a10af6297c203bf549f',
    messagingSenderId: '849429187790',
    projectId: 'barras-762b5',
    storageBucket: 'barras-762b5.firebasestorage.app',
    iosBundleId: 'com.example.codigobarras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HrjHRyRhW4PAlEyZRr2w9ohu-fpwwUY',
    appId: '1:849429187790:web:254b17d5e90cf645bf549f',
    messagingSenderId: '849429187790',
    projectId: 'barras-762b5',
    authDomain: 'barras-762b5.firebaseapp.com',
    storageBucket: 'barras-762b5.firebasestorage.app',
  );
}
